# Generated by Django 2.2.4 on 2019-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190919_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('FEM', 'Female'), ('MAL', 'Male'), ('UNI', 'Unisex')], default='UNI', max_length=3),
        ),
    ]
