# Generated by Django 2.2.5 on 2019-09-15 05:06

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190915_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to=products.models.product_images_path),
        ),
    ]
